version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.1
  gcp-storage: freighthub/gcp-storage@0.2.0
  gcp-gcr: circleci/gcp-gcr@0.15.0
  node: circleci/node@5.0.2
  pulumi: pulumi/pulumi@2.1.0
jobs:
  build-app:
      docker:
        - image: 'cimg/base:stable'
      steps:
        - checkout
        - node/install:
            install-yarn: true
            node-version: '16.14'
        - run: cd pulumi && npm install
        - run: cd web && yarn --frozen-lockfile
        - run: cd web && yarn build:linux
        - persist_to_workspace:
            root: /home/circleci/project
            paths:
              - web
              - pulumi
  push-static-folder:
    executor: gcp-storage/google
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - gcp-cli/install
      - gcp-storage/upload:
          source_path: /home/circleci/project/web/static/*
          destination_bucket: static.holmok.com
          transfer_files_compressed: 'js,css,html'
  build-image-and-push:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          docker-context: ./web
          path: ./web
          workspace-root: ./web
          image: holmok-com
          tag: v$CIRCLE_BUILD_NUM
          no_output_timeout: 20m
          registry-url: us.gcr.io
      - gcp-gcr/push-image:
          image: holmok-com
          registry-url: us.gcr.io
          tag: v$CIRCLE_BUILD_NUM
      - gcp-gcr/tag-image:
          image: holmok-com
          registry-url: us.gcr.io
          source-tag: v$CIRCLE_BUILD_NUM
          target-tag: latest 
  build-infra:
    docker:
      - image: 'circleci/node:10'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: /home/circleci/project 
      - pulumi/login
      - pulumi/update:
          stack:  main
          working_directory: /home/circleci/project/pulumi
workflows:
  main-branch-commit:
    jobs:
      - build-app
      - push-static-folder:
          requires:
              - build-app
      - build-image-and-push: 
          requires:
              - build-app
      - build-infra:
          requires:
              - build-image-and-push
              - push-static-folder
